### ISSUE TITLE
The Thai string ค้นหาใน (Search in) contains "%1$s"

### ISSUE THREAD

**Issue by veer66** [mozilla-tw/Rocket#2227]
The Thai string ค้นหาใน (Search in) contains "%1$s" in build 5748. I tested on Nokia 1.

## Reproduce
1. Long tap for selecting some text
2. Tap the 3-vertical-dot icon

![photo_2018-07-23_22-57-30](https://user-images.githubusercontent.com/370688/43088861-6e4961aa-8ecd-11e8-99b3-5c8c4169260a.jpg)

**Comment by mxlius** [comment]
Fixed in #1825 #2206.

Thanks for filing this issue 👍

**Comment by veer66** [comment]
FYI this issue still affects build 5760. 

![b63a00d9568d25c8](https://user-images.githubusercontent.com/370688/43117898-6afe659c-8f39-11e8-8161-bda3f7a0ddb5.png)

**Comment by mTwTm** [comment]
Yeah, we haven't managed to fix the issue on pontoon so every time we do an import it might occur again if I forgot to manually fix that. If everything goes well we should be able to fix that on Pontoon tomorrow. I'll first fix it manually again and it should be shown normally today. However, I'll leave this issue open until I've done the back to pontoon thing.

**Comment by veer66** [comment]
@mTwTm Thank you. Please let me know after you put it on Pontoon.

**Comment by mTwTm** [comment]
Reopen: Fix this when things are sync backed to Pontoon so we're safe.

**Comment by veer66** [comment]
Build 5802 works.

![image](https://user-images.githubusercontent.com/370688/43181809-14ff77dc-9009-11e8-8b22-c6f58847fcbf.png)

**Comment by mTwTm** [comment]
And yes they're on Pontoon and I've seen you help updated that. I was trying to auto fix them but Pontoon wasn't buying that 😢 Thank you!
